spring:
  cloud:
    gateway:
      routes:
        - id: ms-auth-service
          uri: ${MS_AUTH_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**
            - Path=/api/v1/auth/helper/**
            - Path=/api/v1/users/**

        - id: account-transfer-service
          uri: ${MS_TRANSFER_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/accounts/**
            - Path=/api/v1/rates/**
